### PR TITLE
Support local files and misc fixes

### PR DESCRIPTION
**Pull request by ngaullier**
Thank you for your review, I have integrated all your changes in this new pull request (nothing else modified).
Nicolas

### CODE REVIEW

**Comment by selsta** [comment]
Thank you again, nice to see people use this program :P

**Comment by selsta** [comment]
@ngaullier Can you explain `SAMPLE-AES: Fix reset IV at start of block` ?

Testing with https://demo.unified-streaming.com/video/tears-of-steel/tears-of-steel-sample-aes.ism/.m3u8 this commit seems to produce broken files. I’ve reverted it for now.

**Comment by ngaullier** [comment]
I am very sorry about that. In my files, this is the opposite… The fact is, I had broken files so I tried to reset IV, it worked, and then I started to look at the documentation…
The problem is the documentation is ambiguous (as always with apple : many interop issues with quicktime…)

I read that :

1)      “the initialization vector (IV) must be reset to its original value at the start of each new protected block.”
https://developer.apple.com/library/archive/documentation/AudioVideo/Conceptual/HLS_Sample_Encryption/Encryption/Encryption.html#//apple_ref/doc/uid/TP40012862-CH2-SW6
2) IV for [AES_128] (ie. does not apply to sample-aes!)
https://tools.ietf.org/html/draft-pantos-http-live-streaming-23#section-5.2
An EXT-X-KEY tag with a KEYFORMAT of "identity" that does not have an
   IV attribute indicates that the Media Sequence Number is to be used
   as the IV when decrypting a Media Segment, by putting its big-endian
   binary representation into a 16-octet (128-bit) buffer and padding
   (on the left) with zeros.

I don’t find all of this that clear, but in my understanding, the incrementation of iv does not apply to sample-aes.
So I felt reassured, but you’re right, a sample file from USP should be ok!!!

I guess there is something tricky, not well documented, and sometimes the iv must be reset, and sometimes not. I compared the m3u8 but did not found yet what difference could make that happen :
USP:
#EXT-X-VERSION:4
#EXT-X-SESSION-KEY:METHOD=SAMPLE-AES,URI="https://demo.unified-streaming.com/video/tears-of-steel/aes.key"

Ateme: (our encoder)
#EXT-X-VERSION:5
#EXT-X-SESSION-KEY:METHOD=SAMPLE-AES,URI="<mycustomstring>",KEYFORMAT="com.apple.streamingkeydelivery",KEYFORMATVERSIONS="1"

This is very strange. I will try to gather some more different samples and read the doc again, but I don’t catch for now…

Nicolas
De : selsta [mailto:notifications@github.com]
Envoyé : vendredi 6 septembre 2019 15:12
À : selsta/hlsdl <hlsdl@noreply.github.com>
Cc : Gaullier Nicolas <nicolas.gaullier@arkena.com>; Mention <mention@noreply.github.com>
Objet : Re: [selsta/hlsdl] Support local files and misc fixes (#44)


@ngaullier<https://github.com/ngaullier> Can you explain SAMPLE-AES: Fix reset IV at start of block ?

Testing with https://demo.unified-streaming.com/video/tears-of-steel/tears-of-steel-sample-aes.ism/.m3u8 this commit seems to produce broken files. I’ve reverted it for now.

**Comment by ngaullier** [comment]
I got it.
Look at https://github.com/axiomatic-systems/Bento4/blob/master/Source/C%2B%2B/Apps/Mp42Hls/Mp42Hls.cpp
                if (Options.encryption_iv_mode == ENCRYPTION_IV_MODE_SEQUENCE) {
                    AP4_SetMemory(Options.encryption_iv, 0, sizeof(Options.encryption_iv));
                    AP4_BytesFromUInt32BE(&Options.encryption_iv[12], segment_number);
                }

There as several ENCRYPTION_IV_MODE. The one with autoincrement is called ENCRYPTION_IV_MODE_SEQUENCE in bento4, but the one I use is ENCRYPTION_IV_MODE_FPS  : FPS = Fair Play (indeed, KEYFORMAT="com.apple.streamingkeydelivery" means FairPlay).

So I will come back with a new patch proposal where, when KEYFORMAT="com.apple.streamingkeydelivery", the iv is static, and anything else remain unchanged.

Nicolas
De : Gaullier Nicolas
Envoyé : vendredi 6 septembre 2019 16:10
À : selsta/hlsdl <reply@reply.github.com>
Objet : RE: [selsta/hlsdl] Support local files and misc fixes (#44)

I am very sorry about that. In my files, this is the opposite… The fact is, I had broken files so I tried to reset IV, it worked, and then I started to look at the documentation…
The problem is the documentation is ambiguous (as always with apple : many interop issues with quicktime…)

I read that :

1)      “the initialization vector (IV) must be reset to its original value at the start of each new protected block.”
https://developer.apple.com/library/archive/documentation/AudioVideo/Conceptual/HLS_Sample_Encryption/Encryption/Encryption.html#//apple_ref/doc/uid/TP40012862-CH2-SW6
2) IV for [AES_128] (ie. does not apply to sample-aes!)
https://tools.ietf.org/html/draft-pantos-http-live-streaming-23#section-5.2
An EXT-X-KEY tag with a KEYFORMAT of "identity" that does not have an
   IV attribute indicates that the Media Sequence Number is to be used
   as the IV when decrypting a Media Segment, by putting its big-endian
   binary representation into a 16-octet (128-bit) buffer and padding
   (on the left) with zeros.

I don’t find all of this that clear, but in my understanding, the incrementation of iv does not apply to sample-aes.
So I felt reassured, but you’re right, a sample file from USP should be ok!!!

I guess there is something tricky, not well documented, and sometimes the iv must be reset, and sometimes not. I compared the m3u8 but did not found yet what difference could make that happen :
USP:
#EXT-X-VERSION:4
#EXT-X-SESSION-KEY:METHOD=SAMPLE-AES,URI="https://demo.unified-streaming.com/video/tears-of-steel/aes.key"

Ateme: (our encoder)
#EXT-X-VERSION:5
#EXT-X-SESSION-KEY:METHOD=SAMPLE-AES,URI="<mycustomstring>",KEYFORMAT="com.apple.streamingkeydelivery",KEYFORMATVERSIONS="1"

This is very strange. I will try to gather some more different samples and read the doc again, but I don’t catch for now…

Nicolas
De : selsta [mailto:notifications@github.com]
Envoyé : vendredi 6 septembre 2019 15:12
À : selsta/hlsdl <hlsdl@noreply.github.com<mailto:hlsdl@noreply.github.com>>
Cc : Gaullier Nicolas <nicolas.gaullier@arkena.com<mailto:nicolas.gaullier@arkena.com>>; Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Objet : Re: [selsta/hlsdl] Support local files and misc fixes (#44)


@ngaullier<https://github.com/ngaullier> Can you explain SAMPLE-AES: Fix reset IV at start of block ?

Testing with https://demo.unified-streaming.com/video/tears-of-steel/tears-of-steel-sample-aes.ism/.m3u8 this commit seems to produce broken files. I’ve reverted it for now.

**Pull request merged**
