### PR TITLE
remove png bytes if exists

### PR DESCRIPTION
**Pull request by rabinovic**

### CODE REVIEW

**Comment by selsta** [comment]
Hi, patch looks good. When is this useful?

**Comment by selsta** [comment]
Also please fix the indentation.

**Comment by rabinovic** [comment]
well,
some time ago I tried to find out why some streaming viedeos with m3u8 were
not working, until I came across the article:
https://laurentmeyer.medium.com/deep-dive-in-the-illegal-streaming-world-cd11fae63497
.
Indeed the stream seqments startet with a png header. So if i removed the
png header the video worked.

Am Mo., 19. Apr. 2021 um 19:03 Uhr schrieb selsta ***@***.***

**Comment by selsta** [comment]
Thanks.

**Pull request merged**
